export const errorPages = [
  {
    code: '404',
    title: 'Page not found',
    eyebrow: 'Missing route',
    description: 'The page you requested may have moved, been deleted, or never existed.',
    action: 'Return to dashboard',
    href: '/errors/404.html',
    accent: 'from-blue-600 to-indigo-600',
    guidance: ['Check the URL for typos.', 'Use the dashboard modules to find the resource again.'],
  },
  {
    code: '500',
    title: 'Internal server error',
    eyebrow: 'Unexpected failure',
    description: 'Something went wrong while processing the request. Please try again or contact support if it continues.',
    action: 'Reload dashboard',
    href: '/errors/500.html',
    accent: 'from-rose-600 to-orange-500',
    guidance: ['Refresh the page after a moment.', 'Capture the request ID or timestamp for support.'],
  },
  {
    code: '401',
    title: 'Authentication required',
    eyebrow: 'Sign in needed',
    description: 'Your session is missing or expired. Sign in again to continue managing dashboard data.',
    action: 'Go to dashboard',
    href: '/errors/401.html',
    accent: 'from-amber-500 to-yellow-500',
    guidance: ['Confirm you are signed in.', 'Ask an administrator to restore access if needed.'],
  },
  {
    code: '403',
    title: 'Access forbidden',
    eyebrow: 'Permission denied',
    description: 'You do not have permission to open this area of the admin dashboard.',
    action: 'Back to safe area',
    href: '/errors/403.html',
    accent: 'from-purple-600 to-fuchsia-600',
    guidance: ['Verify the account has the right role.', 'Contact an administrator for elevated access.'],
  },
  {
    code: '503',
    title: 'Service unavailable',
    eyebrow: 'Temporary outage',
    description: 'The service is temporarily unavailable because of maintenance or high traffic.',
    action: 'Retry dashboard',
    href: '/errors/503.html',
    accent: 'from-emerald-600 to-teal-500',
    guidance: ['Wait a minute before retrying.', 'Check operational updates from the team.'],
  },
];
